; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube

; upload_protocol = stlink
; debug_tool = stlink
upload_protocol = blackmagic
debug_tool = blackmagic
upload_port = COM8
; board_build.cmsis = true


build_flags = 
    -Isrc/Core/Inc
    -Isrc/Drivers/CMSIS/Device/ST/STM32F1xx/Include
    -Isrc/Drivers/CMSIS/Include
    ; -Isrc/Drivers/STM32F1xx_HAL_Driver/Inc
    ; -Isrc/Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
    -Isrc/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
    -Isrc/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
    -Isrc/USB_DEVICE/App
    -Isrc/USB_DEVICE/Target



build_src_filter =
    +<Core/Src>
    +<Middlewares/ST/STM32_USB_Device_Library/Class/Src>
    +<Middlewares/ST/STM32_USB_Device_Library/Core/Src>
    +<USB_DEVICE/App>
    +<USB_DEVICE/Target>
    ; -<src/Drivers/STM32F1xx_HAL_Driver/Src>